# Generated by Django 5.2 on 2025-05-05 22:28

from django.db import migrations


def populate_status(apps, schemaeditor):
    entries = {
        "published":"A post anyone can view",
        "draft": "A post visible only to the author",
        "archived": "An older post visible only to logged in users"
    }

    Status = apps.get_model("posts", "Status")

    for key, value in entries.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]
